services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    volumes:
      - sonarr_config:/config
      - media_data:/data
    networks:
      - traefik_public
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.rule: "Host(`sonarr.ragnalab.xyz`)"
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
      traefik.http.routers.sonarr.middlewares: authelia@docker
      kuma.sonarr.http.name: Sonarr
      kuma.sonarr.http.url: https://sonarr.ragnalab.xyz
    restart: unless-stopped

volumes:
  sonarr_config:
    external: true
  media_data:
    external: true

networks:
  traefik_public:
    external: true
