---
# Traefik Reverse Proxy

- name: Create traefik_public network
  community.docker.docker_network:
    name: traefik_public
    driver: bridge

- name: Create traefik_data volume
  community.docker.docker_volume:
    name: traefik_data

- name: Start Traefik
  community.docker.docker_compose_v2:
    project_src: "{{ compose_root }}"
    services:
      - traefik
    state: present
