---
# Traefik Reverse Proxy

- name: Create traefik_public network
  community.docker.docker_network:
    name: traefik_public
    driver: bridge

- name: Create traefik_acme volume
  community.docker.docker_volume:
    name: traefik_acme

- name: Start Traefik
  community.docker.docker_compose_v2:
    project_src: "{{ playbook_dir }}/../compose"
    services:
      - traefik
    state: present
