---
- Services:
    - Traefik:
        href: https://traefik.ragnalab.xyz
        description: Reverse proxy
        server: socket-proxy
        container: traefik
    - Authelia:
        href: https://auth.ragnalab.xyz
        description: SSO authentication
        server: socket-proxy
        container: authelia
    - Pi-hole:
        href: https://pihole.ragnalab.xyz
        description: DNS ad-blocking
        server: socket-proxy
        container: pihole

- Apps:
    - RustDesk:
        description: Remote desktop server
        server: socket-proxy
        container: rustdesk-hbbs
    - Uptime Kuma:
        href: https://uptime.ragnalab.xyz
        description: Uptime monitoring
        server: socket-proxy
        container: uptime-kuma
    - Vaultwarden:
        href: https://vault.ragnalab.xyz
        description: Password manager
        server: socket-proxy
        container: vaultwarden
    - Paperless-ngx:
        href: https://paperless.ragnalab.xyz
        description: Document management
        server: socket-proxy
        container: paperless-ngx
    - Ntfy:
        href: https://ntfy.ragnalab.xyz
        description: Push notifications
        server: socket-proxy
        container: ntfy
    - Tandoor Recipes:
        href: https://recipes.ragnalab.xyz
        description: Recipe manager
        server: socket-proxy
        container: tandoor
    - Dozzle:
        href: https://logs.ragnalab.xyz
        description: Docker log viewer
        server: socket-proxy
        container: dozzle

- Media:
    - Jellyfin:
        href: https://jellyfin.ragnalab.xyz
        description: Media server
        server: socket-proxy
        container: jellyfin
    - Jellyseerr:
        href: https://requests.ragnalab.xyz
        description: Media requests
        server: socket-proxy
        container: jellyseerr
    - Sonarr:
        href: https://sonarr.ragnalab.xyz
        description: TV show management
        server: socket-proxy
        container: sonarr
    - Radarr:
        href: https://radarr.ragnalab.xyz
        description: Movie management
        server: socket-proxy
        container: radarr
    - Bazarr:
        href: https://bazarr.ragnalab.xyz
        description: Subtitle management
        server: socket-proxy
        container: bazarr
    - Prowlarr:
        href: https://prowlarr.ragnalab.xyz
        description: Indexer management
        server: socket-proxy
        container: prowlarr
    - qBittorrent:
        href: https://qbit.ragnalab.xyz
        description: Torrent client
        server: socket-proxy
        container: gluetun
