---
# Top bar widgets

- logo:
    icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/homelab.png

- greeting:
    text_size: xl
    text: "Welcome to RagnaLab"

- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false

- resources:
    label: System
    expanded: true
    cpu: true
    memory: true
    disk: /
    diskUnits: bytes
    uptime: true
