$ANSIBLE_VAULT;1.1;AES256
39626166323636643533383165316636353533653038343834366637623062326238643365363265
3363383064353939663562333235306461666337643063660a343231636537326565353363343034
39626463383230353730623362323937323039303663633463313937306266343366336236386366
6132336337623233620a363135363936646330376530646566393061356136613039393062366439
65376631333635333833653164643431356262396439363966383632663663666461383035376433
66633032363534623762656536636362373861333665643730393638663761333664636532383530
66343035393233373334383434363739356539623337373666613234353331336139383336316436
37383238616665386232646235373664386663393963386135323064303366386136656136356330
3934
