$ANSIBLE_VAULT;1.1;AES256
38363837303532303861386566616538366531616132373965323263356234646335656630643135
3764646163373263323335643834356137336561303838390a666561346666306439663033643864
38376337376363626637383736316265336230663762326434376430333639366363353731353431
3036373661366166390a326239633666393361333763393066396561326365623831633335326631
64643464386336653738396438373563323061393338363764656363313238363834663561386664
38666562666562373861333366383364333430353064313035326537313230626534393835346361
33643462323565396230343138323635363566636639326265303731336562333963316139653435
38656139656465613366383266343239323230373965356465366261346537383765646532653032
62636665663732316162343133316663616663326633323435666238623135646437663137666565
38333536306337313339363230613663346631626165663337656566626636623134626666316562
61633734356139356463663834393634623335633835343665623037386664626337336135396439
62343762303866383039373964616661306366653536313432336464386461636161633462366461
65636662663039633636393133633534313061313263323034643139306563366130353331333239
32383731366530363638343133316266666363643264366238326236363666333136343538393538
36633063306662653338636363613363313464396331383337313330346537623037393734333638
66346536383433373563653262663336643139376663363737333065393131663061663438303537
64623166366632336262323430323139373762343462366662656534316636376438373831376335
39653332643937653564623965643565616638613630613133613435646561333732336538383437
62326631363135316564663466353561343239623431396331623639323262373435396435643036
30343766373039643931
