---
# Actual Budget

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: create-volumes
    volumes: [actual_data]

- name: Start Actual Budget
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: start
    services: [actual-budget]
