---
# FileBrowser

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    action: create-volumes
    volumes: [filebrowser_db, filebrowser_data]

- name: Start FileBrowser
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    action: start
    services: [filebrowser]
