---
# FreshRSS

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    action: create-volumes
    volumes: [freshrss_data]

- name: Start FreshRSS
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    action: start
    services: [freshrss]
