---
# FreshRSS

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: create-volumes
    volumes: [freshrss_data]

- name: Start FreshRSS
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: start
    services: [freshrss]
