---
# Home Assistant

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: create-volumes
    volumes: [homeassistant_config]

- name: Start Home Assistant
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: start
    services: [homeassistant]
