---
# Jellyseerr

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    action: create-volumes
    volumes: [jellyseerr_config]

- name: Start Jellyseerr
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    action: start
    services: [jellyseerr]

- name: Jellyseerr post-deploy
  ansible.builtin.debug:
    msg: "Jellyseerr deployed. Complete the setup wizard at https://requests.ragnalab.xyz"
