---
# Ntfy

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: create-volumes
    volumes: [ntfy_cache]

- name: Start Ntfy
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: start
    services: [ntfy]
