---
# Speedtest Tracker

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    action: create-volumes
    volumes: [speedtest_data]

- name: Start Speedtest Tracker
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    action: start
    services: [speedtest-tracker]
