---
# Tandoor Recipes

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: create-volumes
    volumes:
      - tandoor_data

- name: Start Tandoor Recipes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: start
    services: [tandoor, tandoor-db]
