---
# Uptime Kuma + AutoKuma

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: create-volumes
    volumes: [uptime_kuma_data]

- name: Start Uptime Kuma + AutoKuma
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: start
    services: [uptime-kuma, autokuma]
