---
# Vaultwarden

- name: Create vaultwarden_data volume
  community.docker.docker_volume:
    name: vaultwarden_data

- name: Start Vaultwarden
  community.docker.docker_compose_v2:
    project_src: "{{ playbook_dir }}/../compose"
    services:
      - vaultwarden
    state: present
