---
# Vaultwarden

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    action: create-volumes
    volumes: [vaultwarden_data]

- name: Start Vaultwarden
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    action: start
    services: [vaultwarden]
