---
# Vaultwarden

- name: Create volumes
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: create-volumes
    volumes: [vaultwarden_data]

- name: Start Vaultwarden
  ansible.builtin.include_tasks: ../shared/helpers.yml
  vars:
    helper: start
    services: [vaultwarden]
