include:
  - services/socket-proxy/docker-compose.yml
  - services/authelia/docker-compose.yml
  - services/traefik/docker-compose.yml
  - services/pihole/docker-compose.yml
  - apps/rustdesk/docker-compose.yml
  - apps/uptime-kuma/docker-compose.yml
  - apps/homepage/docker-compose.yml
  - apps/vaultwarden/docker-compose.yml
  - apps/paperless-ngx/docker-compose.yml
  - apps/ntfy/docker-compose.yml
  - apps/tandoor/docker-compose.yml
  - apps/dozzle/docker-compose.yml
  - apps/qbittorrent/docker-compose.yml
  - apps/prowlarr/docker-compose.yml
  - apps/sonarr/docker-compose.yml
  - apps/radarr/docker-compose.yml
  - apps/bazarr/docker-compose.yml
  - apps/jellyfin/docker-compose.yml
  - apps/jellyseerr/docker-compose.yml
  - apps/freshrss/docker-compose.yml
  - apps/actual-budget/docker-compose.yml
  - apps/obsidian-livesync/docker-compose.yml
  - apps/syncthing/docker-compose.yml
  - apps/filebrowser/docker-compose.yml
  - apps/backrest/docker-compose.yml
  - apps/beszel/docker-compose.yml
  - apps/homeassistant/docker-compose.yml
  - apps/speedtest-tracker/docker-compose.yml
