services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      FB_NOAUTH: "true"
    volumes:
      - filebrowser_db:/database
      - filebrowser_data:/srv
    networks:
      - traefik_public
    labels:
      traefik.enable: "true"
      traefik.http.routers.filebrowser.rule: "Host(`files.${DOMAIN}`)"
      traefik.http.routers.filebrowser.entrypoints: websecure
      traefik.http.services.filebrowser.loadbalancer.server.port: "80"
      traefik.http.routers.filebrowser.middlewares: authelia@docker
      kuma.filebrowser.http.name: FileBrowser
      kuma.filebrowser.http.url: https://files.${DOMAIN}
    deploy:
      resources:
        limits:
          memory: 128M
    restart: unless-stopped

volumes:
  filebrowser_db:
    external: true
  filebrowser_data:
    external: true

networks:
  traefik_public:
    external: true
