---
server:
  address: "tcp://:9091"

log:
  level: info

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor
  rules:
    - domain: auth.ragnalab.xyz
      policy: bypass
    - domain: vault.ragnalab.xyz
      policy: bypass
    - domain: ntfy.ragnalab.xyz
      policy: bypass
    - domain: jellyfin.ragnalab.xyz
      policy: bypass
    - domain: requests.ragnalab.xyz
      policy: bypass

session:
  cookies:
    - domain: ragnalab.xyz
      authelia_url: https://auth.ragnalab.xyz

storage:
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /data/notification.txt
